### PR TITLE
Fix issue with mutated code block

### LINKED ISSUE #312: Cache explorer not updating on new values
## About

The cache explorer content isn't changing automatically - almost definitely an issue with the [CodeHighlight component](https://github.com/FormidableLabs/urql-devtools/blob/master/src/panel/components/CodeHighlight.tsx#L12)

Thanks to @hhastekin for finding this one

### PR DESCRIPTION
**Pull request by andyrichardson**
## About

Fix #312

### CODE REVIEW

File: src/panel/components/CodeHighlight.tsx [hunk 1]
```diff
@@ -11,26 +11,29 @@ export const CodeHighlight: FC<
 > = ({ code, language, ...props }) => {
   const handleRef = useCallback(
     (ref: HTMLPreElement | null) => {
-      if (ref === null) {
+      if (!ref) {
         return;
       }
 
-      (ref.children[0] as HTMLElement).textContent = code;
```
Comment (andyrichardson) [inline src/panel/components/CodeHighlight.tsx:18]: Issue was because this line was missing on the component below.

Making the change anyway to ensure we create a fresh code element on each update.

**Review by kadikraman — APPROVED** [review]

**Review by wgolledge — APPROVED** [review]
