### PR TITLE
Fix vertical overflow on timeline

### LINKED ISSUE #177: No vertical scrolling on the timeline
## About

The timeline breaks on vertical overflow

Kapture 2020-04-29 at 17 33 04

### PR DESCRIPTION
**Pull request by andyrichardson**
## About

Fix #177

## Screenshots
Kapture 2020-04-30 at 10 41 07

### CODE REVIEW

File: src/panel/pages/events/Timeline.tsx [hunk 1]
```diff
@@ -220,12 +228,15 @@ const TimelineIcons = styled.div`
...
-  display: flex;
-  flex-direction: column;
-  flex-grow: 1;
+  display: block;
   position: relative;
   padding: 70px 0;
-  overflow: hidden;
+  overflow-y: visible;
+  width: 100%;
+  box-sizing: border-box;
```
Comment (wgolledge) [inline src/panel/pages/events/Timeline.tsx:236]: Not that it really matters, but I think alphabeticalising(?) css props can help keep them at least somewhat organised

Comment (andyrichardson) [reply src/panel/pages/events/Timeline.tsx:236]: Would be cool if prettier could do this - do you have examples of repos that use this? 

I can see the advantages - sometimes I group by type (e.g. color, positioning) but I'm not consistent with that.

Comment (wgolledge) [reply src/panel/pages/events/Timeline.tsx:236]: No concrete examples to hand - I don't think there's a defacto standard

I just found [this post](https://dev.to/thekashey/happy-potter-and-the-order-of-css-5ec) that was a fairly interesting read, and mentions [stylelint-config-rational-order](https://www.npmjs.com/package/stylelint-config-rational-order) and [stylelint-order](https://www.npmjs.com/package/stylelint-order) which could be useful if using `stylelint`
